name: Run Pytest Automatically

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout Code
      uses: actions/checkout@v4

    - name: Step 2 - Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Step 3 - Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Step 4 - Run tests with pytest
      run: |
        pytest --junitxml=reports/test-results.xml

    - name: Step 5 - Upload report to GitHub
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/test-results.xml
